name: Webpage to PDF 
on: [push]
jobs:
  Webpage-to-PDF:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Webpage to PDF
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: https://lernraum-toolkit.github.io/
          outputFile: ./test.pdf
          usePuppeteer: true
          useScreen: true
          pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - run: echo "ğŸ This job's status is ${{ job.status }}."
